import { useState } from 'react';
import Banner from './componentes/Banner';
import Form from './componentes/Form';
import Team from './componentes/Team';
import Footer from './componentes/Footer';

import { v4 as uuidv4 } from 'uuid';

function App() {

  const [teams, setTeams] = useState([
    {
      id: uuidv4(),
      name: 'Atlanta Hawks',
      color: '#EB425F',
      championships: '1x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Boston Celtics',
      color: '#3F9971',
      championships: '17x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Brooklyn Nets',
      color: '#303030',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'Charlotte Hornets',
      color: '#5E9FAD',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'Chicago Bulls',
      color: '#EB425F',
      championships: '6x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Cleveland Cavaliers',
      color: '#803049',
      championships: '1x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Dallas Mavericks',
      color: '#3775AF',
      championships: '1x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Denver Nuggets',
      color: '#23375A',
      championships: '1x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Detroit Pistons',
      color: '#336BAB',
      championships: '3x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Golden State Warriors',
      color: '#FFCC3D',
      championships: '7x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Houston Rockets',
      color: '#FF305E',
      championships: '2x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Indiana Pacers',
      color: '#FFC854',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'Los Angeles Clippers',
      color: '#1C2B40',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'Los Angeles Lakers',
      color: '#FFC72C',
      championships: '17x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Memphis Grizzlies',
      color: '#426299',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'Miami Heat',
      color: '#C23A62',
      championships: '3x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Milwaukee Bucks',
      color: '#205032',
      championships: '2x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Minnesota Timberwolves',
      color: '#1C2E47',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'New Orleans Pelicans',
      color: '#F44D65',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'New York Knicks',
      logo: '2x NBA Champions',
      color: '#FF8E33',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'Oklahoma City Thunder',
      color: '#FF7357',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'Orlando Magic',
      color: '#64AAD8',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'Philadelphia 76ers',
      color: '#446099',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'Phoenix Suns',
      color: '#F67E3F',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'Portland Trail Blazers',
      color: '#DD4862',
      championships: '1x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Sacramento Kings',
      color: '#7E579D',
      championships: '1x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'San Antonio Spurs',
      color: '#545454',
      championships: '5x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Toronto Raptors',
      color: '#CF4A4F',
      championships: '1x NBA Champions',
    },
    {
      id: uuidv4(),
      name: 'Utah Jazz',
      color: '#29415B',
      championships: '',
    },
    {
      id: uuidv4(),
      name: 'Washington Wizards',
      color: '#F43753',
      championships: '',
    }
  ]);

  const starters = [
    {
      id: uuidv4(),
      name: 'Trae Young',
      position: 'PG',
      highSchool: 'Norman North',
      draftPick: '#5',
      draftedBy: 'Atlanta Hawks',
      team: teams[0].name,
    },
    {
      id: uuidv4(),
      name: 'Dejounte Murray',
      position: 'PG | SG',
      highSchool: 'Rainier Beach',
      draftPick: '#29',
      draftedBy: 'San Antonio Spurs',
      team: teams[0].name,
    },
    {
      id: uuidv4(),
      name: 'Bojan Bogdanovic',
      position: 'SF | PF',
      highSchool: 'Fenerbahçe (Türkiye)',
      draftPick: '#31',
      draftedBy: 'Miami Heat',
      team: teams[0].name,
    },
    {
      id: uuidv4(),
      name: 'Jalen Johnson',
      position: 'SF | PF',
      highSchool: 'Sun Prairie',
      draftPick: '#20',
      draftedBy: 'Atlanta Hawks',
      team: teams[0].name,
    },
    {
      id: uuidv4(),
      name: 'Clint Capela',
      position: 'C',
      highSchool: 'Elan Chalon (France)',
      draftPick: '#25',
      draftedBy: 'Houston Rockets',
      team: teams[0].name,
    },
    {
      id: uuidv4(),
      name: 'Jayson Tatum',
      position: 'SF | PF',
      highSchool: 'Chaminade College',
      draftPick: '#3',
      draftedBy: 'Boston Celtics',
      team: teams[1].name,
    },
    {
      id: uuidv4(),
      name: 'Jaylen Brown',
      position: 'SG | SF',
      highSchool: 'Wheeler',
      draftPick: '#3',
      draftedBy: 'Boston Celtics',
      team: teams[1].name,
    },
    {
      id: uuidv4(),
      name: 'Derrick White',
      position: 'PG | SG',
      highSchool: 'Legend',
      draftPick: '#29',
      draftedBy: 'San Antonio Spurs',
      team: teams[1].name,
    },
    {
      id: uuidv4(),
      name: 'Kristaps Porzingis',
      position: 'PF | C',
      highSchool: 'Sevilla (Spain)',
      draftPick: '#4',
      draftedBy: 'New York Knicks',
      team: teams[1].name,
    },
    {
      id: uuidv4(),
      name: 'Jrue Holiday',
      position: 'PG | SG',
      highSchool: 'Campbell Hall',
      draftPick: '#17',
      draftedBy: 'Philadelphia 76ers',
      team: teams[1].name,
    },
    {
      id: uuidv4(),
      name: 'Nicolas Claxton',
      position: 'PF | C',
      highSchool: 'Legacy Charter',
      draftPick: '#31',
      draftedBy: 'Brooklyn Nets',
      team: teams[2].name,
    },
    {
      id: uuidv4(),
      name: 'Cameron Thomas',
      position: 'SG',
      highSchool: 'Oak Hill Academy',
      draftPick: '#27',
      draftedBy: 'Brooklyn Nets',
      team: teams[2].name,
    },
    {
      id: uuidv4(),
      name: 'Mikal Bridges',
      position: 'SF | SG',
      highSchool: 'Great Valley',
      draftPick: '#10',
      draftedBy: 'Philadelphia 76ers',
      team: teams[2].name,
    },
    {
      id: uuidv4(),
      name: 'Dennis Schroder',
      position: 'PG | SG',
      highSchool: 'Braunschweig (Germany)',
      draftPick: '#17',
      draftedBy: 'Atlanta Hawks',
      team: teams[2].name,
    },
    {
      id: uuidv4(),
      name: 'Dorian Finney-Smith',
      position: 'SF | PF',
      highSchool: 'Norcom',
      draftPick: 'Undrafted',
      draftedBy: '',
      team: teams[2].name,
    },
    {
      id: uuidv4(),
      name: 'LaMelo Ball',
      position: 'PG',
      highSchool: 'Chino Hills',
      draftPick: '#3',
      draftedBy: 'Charlotte Hornets',
      team: teams[3].name,
    },
    {
      id: uuidv4(),
      name: 'Cody Martin',
      position: 'SG | SF',
      highSchool: 'Oak Hill Academy',
      draftPick: '#36',
      draftedBy: 'Charlotte Hornets',
      team: teams[3].name,
    },
    {
      id: uuidv4(),
      name: 'Brandon Miller',
      position: 'SF',
      highSchool: 'Cane Ridge',
      draftPick: '#2',
      draftedBy: 'Charlotte Hornets',
      team: teams[3].name,
    },
    {
      id: uuidv4(),
      name: 'Miles Bridges',
      position: 'SF | PF',
      highSchool: 'Huntington Prep',
      draftPick: '#12',
      draftedBy: 'Los Angeles Clippers',
      team: teams[3].name,
    },
    {
      id: uuidv4(),
      name: 'Mark Williams',
      position: 'C',
      highSchool: 'IMG Academy',
      draftPick: '#15',
      draftedBy: 'Charlotte Hornets',
      team: teams[3].name,
    },
    {
      id: uuidv4(),
      name: 'Zach LaVine',
      position: 'PG | SG | SF',
      highSchool: 'Bothell',
      draftPick: '#13',
      draftedBy: 'Minnesota Timberwolves',
      team: teams[4].name,
    },
    {
      id: uuidv4(),
      name: 'Alex Caruso',
      position: 'PG | SG',
      highSchool: 'A&M Consolidated',
      draftPick: 'Undrafted',
      draftedBy: '',
      team: teams[4].name,
    },
    {
      id: uuidv4(),
      name: 'Demar DeRozan',
      position: 'SG | SF | PF',
      highSchool: 'Compton',
      draftPick: '#9',
      draftedBy: 'Toronto Raptors',
      team: teams[4].name,
    },
    {
      id: uuidv4(),
      name: 'Coby White',
      position: 'PG | SG',
      highSchool: 'Greenfield',
      draftPick: '#7',
      draftedBy: 'Chicago Bulls',
      team: teams[4].name,
    },
    {
      id: uuidv4(),
      name: 'Nikola Vucevic',
      position: 'C',
      highSchool: 'Stoneridge Prep',
      draftPick: '#16',
      draftedBy: 'Philadelphia 76ers',
      team: teams[4].name,
    },
    {
      id: uuidv4(),
      name: 'Darius Garland',
      position: 'PG | SG',
      highSchool: 'Brentwood Academy',
      draftPick: '#5',
      draftedBy: 'Cleveland Cavaliers',
      team: teams[5].name,
    },
    {
      id: uuidv4(),
      name: 'Donovan Mitchell',
      position: 'PG | SG',
      highSchool: 'Brewster Academy',
      draftPick: '#13',
      draftedBy: 'Denver Nuggets',
      team: teams[5].name,
    },
    {
      id: uuidv4(),
      name: 'Evan Mobley',
      position: 'PF',
      highSchool: 'Rancho Christian',
      draftPick: '#3',
      draftedBy: 'Cleveland Cavaliers',
      team: teams[5].name,
    },
    {
      id: uuidv4(),
      name: 'Jarrett Allen',
      position: 'C',
      highSchool: 'St. Stephen\'s Episcopal School',
      draftPick: '#22',
      draftedBy: 'Brooklyn Nets',
      team: teams[5].name,
    },
    {
      id: uuidv4(),
      name: 'Max Strus',
      position: 'SF',
      highSchool: 'Stagg',
      draftPick: 'Undrafted',
      draftedBy: '',
      team: teams[5].name,
    },
    {
      id: uuidv4(),
      name: 'Luka Doncic',
      position: 'PG | SG',
      highSchool: 'Real Madrid (Spain)',
      draftPick: '#3',
      draftedBy: 'Dallas Mavericks',
      team: teams[6].name,
    },
    {
      id: uuidv4(),
      name: 'Kyrie Irving',
      position: 'PG | SG',
      highSchool: 'St. Patrick',
      draftPick: '#1',
      draftedBy: 'Cleveland Cavaliers',
      team: teams[6].name,
    },
    {
      id: uuidv4(),
      name: 'Derrick Jones Jr.',
      position: 'SF | PF',
      highSchool: 'Archbishop Carroll',
      draftPick: 'Undrafted',
      draftedBy: '',
      team: teams[6].name,
    },
    {
      id: uuidv4(),
      name: 'P.J. Washington',
      position: 'PF | C',
      highSchool: 'Findlay Prep',
      draftPick: '#12',
      draftedBy: 'Charlotte Hornets',
      team: teams[6].name,
    },
    {
      id: uuidv4(),
      name: 'Dereck Lively II',
      position: 'C',
      highSchool: 'Westtown School',
      draftPick: '#12',
      draftedBy: 'Dallas Mavericks',
      team: teams[6].name,
    },
    {
      id: uuidv4(),
      name: 'Nikola Jokic',
      position: 'C',
      highSchool: 'Mega Basket (Serbia)',
      draftPick: '#41',
      draftedBy: 'Denver Nuggets',
      team: teams[7].name,
    },
    {
      id: uuidv4(),
      name: 'Jamal Murray',
      position: 'PG | SG',
      highSchool: 'Orangeville Prep',
      draftPick: '#7',
      draftedBy: 'Denver Nuggets',
      team: teams[7].name,
    },
    {
      id: uuidv4(),
      name: 'Aaron Gordon',
      position: 'SF | PF',
      highSchool: 'Archbishop Mitty',
      draftPick: '#4',
      draftedBy: 'Orlando Magic',
      team: teams[7].name,
    },
    {
      id: uuidv4(),
      name: 'Michael Porter Jr.',
      position: 'SF | PF',
      highSchool: 'Nathan Hale',
      draftPick: '#14',
      draftedBy: 'Denver Nuggets',
      team: teams[7].name,
    },
    {
      id: uuidv4(),
      name: 'Kentavious Caldwell-Pope',
      position: 'SG',
      highSchool: 'Greenville',
      draftPick: '#8',
      draftedBy: 'Detroit Pistons',
      team: teams[7].name,
    },
    {
      id: uuidv4(),
      name: 'Cade Cunningham',
      position: 'PG | SG',
      highSchool: 'Montverde Academy',
      draftPick: '#1',
      draftedBy: 'Detroit Pistons',
      team: teams[8].name,
    },
    {
      id: uuidv4(),
      name: 'Jaden Ivey',
      position: 'SG',
      highSchool: 'La Lumiere School',
      draftPick: '#14',
      draftedBy: 'Detroit Pistons',
      team: teams[8].name,
    },
    {
      id: uuidv4(),
      name: 'Ausar Thompson',
      position: 'SF',
      highSchool: 'Overtime Elite',
      draftPick: '#5',
      draftedBy: 'Detroit Pistons',
      team: teams[8].name,
    },
    {
      id: uuidv4(),
      name: 'Simone Fontecchio',
      position: 'SF',
      highSchool: 'Virtus Bologna (Italy)',
      draftPick: 'Undrafted',
      draftedBy: '',
      team: teams[8].name,
    },
    {
      id: uuidv4(),
      name: 'Jalen Duren',
      position: 'C',
      highSchool: 'Montverde Academy',
      draftPick: '#13',
      draftedBy: 'Charlotte Hornets',
      team: teams[8].name,
    },
    {
      id: uuidv4(),
      name: 'Stephen Curry',
      position: 'PG',
      highSchool: 'Charlotte Christian',
      draftPick: '#7',
      draftedBy: 'Golden State Warriors',
      team: teams[9].name,
    },
    {
      id: uuidv4(),
      name: 'Klay Thompson',
      position: 'SG | SF',
      highSchool: 'Santa Margarita Catholic',
      draftPick: '#11',
      draftedBy: 'Golden State Warriors',
      team: teams[9].name,
    },
    {
      id: uuidv4(),
      name: 'Andrew Wiggins',
      position: 'SF | PF',
      highSchool: 'Huntington Prep',
      draftPick: '#1',
      draftedBy: 'Cleveland Cavaliers',
      team: teams[9].name,
    },
    {
      id: uuidv4(),
      name: 'Draymond Green',
      position: 'SF | PF',
      highSchool: 'Saginaw',
      draftPick: '#35',
      draftedBy: 'Golden State Warriors',
      team: teams[9].name,
    },
    {
      id: uuidv4(),
      name: 'Trayce Jackson-Davis',
      position: 'PF | C',
      highSchool: 'Center Grove',
      draftPick: '#57',
      draftedBy: 'Washington Wizards',
      team: teams[9].name,
    },
    {
      id: uuidv4(),
      name: 'Jalen Green',
      position: 'SG',
      highSchool: 'Prolific Prep',
      draftPick: '#2',
      draftedBy: 'Houston Rockets',
      team: teams[10].name,
    },
    {
      id: uuidv4(),
      name: 'Fred VanVleet',
      position: 'PG | SG',
      highSchool: 'Auburn',
      draftPick: 'Undrafted',
      draftedBy: '',
      team: teams[10].name,
    },
    {
      id: uuidv4(),
      name: 'Dillon Brooks',
      position: 'SG | SF',
      highSchool: 'Findlay Prep',
      draftPick: '#45',
      draftedBy: 'Houston Rockets',
      team: teams[10].name,
    },
    {
      id: uuidv4(),
      name: 'Jabari Smith Jr.',
      position: 'PF',
      highSchool: 'Sandy Creek',
      draftPick: '#3',
      draftedBy: 'Houston Rockets',
      team: teams[10].name,
    },
    {
      id: uuidv4(),
      name: 'Alperen Sengun',
      position: 'C',
      highSchool: 'Beşiktaş (Türkiye)',
      draftPick: '#16',
      draftedBy: 'Oklahoma City Thunder',
      team: teams[10].name,
    },
    {
      id: uuidv4(),
      name: 'Tyrese Haliburton',
      position: 'PG | SG',
      highSchool: 'Oshkosh North',
      draftPick: '#12',
      draftedBy: 'Sacramento Kings',
      team: teams[11].name,
    },
    {
      id: uuidv4(),
      name: 'Andrew Nembhard',
      position: 'PG | SG',
      highSchool: 'Montverde Academy',
      draftPick: '#31',
      draftedBy: 'Indiana Pacers',
      team: teams[11].name,
    },
    {
      id: uuidv4(),
      name: 'Aaron Nesmith',
      position: 'SF',
      highSchool: 'Porter-Gaud',
      draftPick: '#14',
      draftedBy: 'Boston Celtics',
      team: teams[11].name,
    },
    {
      id: uuidv4(),
      name: 'Pascal Siakam',
      position: 'PF',
      highSchool: 'God\'s Academy',
      draftPick: '#27',
      draftedBy: 'Toronto Raptors',
      team: teams[11].name,
    },
    {
      id: uuidv4(),
      name: 'Myles Turner',
      position: 'C',
      highSchool: 'Trinity',
      draftPick: '#11',
      draftedBy: 'Indiana Pacers',
      team: teams[11].name,
    },
    {
      id: uuidv4(),
      name: 'James Harden',
      position: 'PG | SG',
      highSchool: 'Artesia',
      draftPick: '#3',
      draftedBy: 'Oklahoma City Thunder',
      team: teams[12].name,
    },
    {
      id: uuidv4(),
      name: 'Terance Mann',
      position: 'SG | SF',
      highSchool: 'Tilton School',
      draftPick: '#48',
      draftedBy: 'Los Angeles Clippers',
      team: teams[12].name,
    },
    {
      id: uuidv4(),
      name: 'Paul George',
      position: 'SG | SF | PF',
      highSchool: 'Knight',
      draftPick: '#10',
      draftedBy: 'Indiana Pacers',
      team: teams[12].name,
    },
    {
      id: uuidv4(),
      name: 'Kawhi Leonard',
      position: 'SF | PF',
      highSchool: 'King',
      draftPick: '#15',
      draftedBy: 'Indiana Pacers',
      team: teams[12].name,
    },
    {
      id: uuidv4(),
      name: 'Ivica Zubac',
      position: 'C',
      highSchool: 'Mega Basket (Serbia)',
      draftPick: '#32',
      draftedBy: 'Los Angeles Lakers',
      team: teams[12].name,
    },
    {
      id: uuidv4(),
      name: 'D\'Angelo Russell',
      position: 'PG',
      highSchool: 'Montverde Academy',
      draftPick: '#2',
      draftedBy: 'Los Angeles Lakers',
      team: teams[13].name,
    },
    {
      id: uuidv4(),
      name: 'Austin Reaves',
      position: 'SG',
      highSchool: 'Cedar Ridge',
      draftPick: 'Undrafted',
      draftedBy: '',
      team: teams[13].name,
    },
    {
      id: uuidv4(),
      name: 'Lebron James',
      position: 'PG | SG | SF | PF | C',
      highSchool: 'St. Vincent-St. Mary',
      draftPick: '#1',
      draftedBy: 'Cleveland Cavaliers',
      team: teams[13].name,
    },
    {
      id: uuidv4(),
      name: 'Rui Hachimura',
      position: 'SF | PF',
      highSchool: 'Meisei (Japan)',
      draftPick: '#9',
      draftedBy: 'Washington Wizards',
      team: teams[13].name,
    },
    {
      id: uuidv4(),
      name: 'Anthony Davis',
      position: 'PF | C',
      highSchool: 'Perspectives Charter',
      draftPick: '#1',
      draftedBy: 'New Orleans Pelicans',
      team: teams[13].name,
    },
    {
      id: uuidv4(),
      name: 'Ja Morant',
      position: 'PG',
      highSchool: 'Crestwood',
      draftPick: '#2',
      draftedBy: 'Memphis Grizzlies',
      team: teams[14].name,
    },
    {
      id: uuidv4(),
      name: 'Marcus Smart',
      position: 'PG | SG',
      highSchool: 'Edward S. Marcus',
      draftPick: '#6',
      draftedBy: 'Boston Celtics',
      team: teams[14].name,
    },
    {
      id: uuidv4(),
      name: 'Desmond Bane',
      position: 'SG | SF',
      highSchool: 'Seton Catholic',
      draftPick: '#30',
      draftedBy: 'Boston Celtics',
      team: teams[14].name,
    },
    {
      id: uuidv4(),
      name: 'Vince Williams Jr.',
      position: 'SG',
      highSchool: 'St. John\'s College',
      draftPick: '#30',
      draftedBy: 'Memphis Grizzlies',
      team: teams[14].name,
    },
    {
      id: uuidv4(),
      name: 'Jaren Jackson Jr.',
      position: 'PF | C',
      highSchool: 'La Lumiere School',
      draftPick: '#4',
      draftedBy: 'Memphis Grizzlies',
      team: teams[14].name,
    },
    {
      id: uuidv4(),
      name: 'Jimmy Butler',
      position: 'SG | SF | PF',
      highSchool: 'Tomball',
      draftPick: '#30',
      draftedBy: 'Chicago Bulls',
      team: teams[15].name,
    },
    {
      id: uuidv4(),
      name: 'Terry Rozier',
      position: 'PG | SG',
      highSchool: 'Hargrave Military Academy',
      draftPick: '#16',
      draftedBy: 'Boston Celtics',
      team: teams[15].name,
    },
    {
      id: uuidv4(),
      name: 'Tyler Herro',
      position: 'SG',
      highSchool: 'Whitnall',
      draftPick: '#13',
      draftedBy: 'Miami Heat',
      team: teams[15].name,
    },
    {
      id: uuidv4(),
      name: 'Nikola Jovic',
      position: 'PF',
      highSchool: 'Mega Basket (Serbia)',
      draftPick: '#27',
      draftedBy: 'Miami Heat',
      team: teams[15].name,
    },
    {
      id: uuidv4(),
      name: 'Bam Adebayo',
      position: 'PF | C',
      highSchool: 'Northside',
      draftPick: '#14',
      draftedBy: 'Miami Heat',
      team: teams[15].name,
    },
    {
      id: uuidv4(),
      name: 'Damian Lillard',
      position: 'PG',
      highSchool: 'Oakland',
      draftPick: '#6',
      draftedBy: 'Portland Trail Blazers',
      team: teams[16].name,
    },
    {
      id: uuidv4(),
      name: 'Patrick Beverley',
      position: 'PG | SG',
      highSchool: 'Marshall',
      draftPick: '#42',
      draftedBy: 'Los Angeles Lakers',
      team: teams[16].name,
    },
    {
      id: uuidv4(),
      name: 'Khris Middleton',
      position: 'SG | SF',
      highSchool: 'Porter-Gaud',
      draftPick: '#39',
      draftedBy: 'Detroit Pistons',
      team: teams[16].name,
    },
    {
      id: uuidv4(),
      name: 'Giannis Antetokounmpo',
      position: 'SF | PF | C',
      highSchool: 'Filathlitikos (Greece)',
      draftPick: '#15',
      draftedBy: 'Milwaukee Bucks',
      team: teams[16].name,
    },
    {
      id: uuidv4(),
      name: 'Brook Lopez',
      position: 'C',
      highSchool: 'San Joaquin Memorial',
      draftPick: '#10',
      draftedBy: 'New Jersey Nets',
      team: teams[16].name,
    },
    {
      id: uuidv4(),
      name: 'Mike Conley',
      position: 'PG',
      highSchool: 'Lawrence North',
      draftPick: '#4',
      draftedBy: 'Memphis Grizzlies',
      team: teams[17].name,
    },
    {
      id: uuidv4(),
      name: 'Anthony Edwards',
      position: 'SG',
      highSchool: 'Holy Spirit Prep',
      draftPick: '#1',
      draftedBy: 'Minnesota Timberwolves',
      team: teams[17].name,
    },
    {
      id: uuidv4(),
      name: 'Jaden McDaniels',
      position: 'SF | PF',
      highSchool: 'Federal Way',
      draftPick: '#28',
      draftedBy: 'Los Angeles Lakers',
      team: teams[17].name,
    },
    {
      id: uuidv4(),
      name: 'Karl-Anthony Towns',
      position: 'PF | C',
      highSchool: 'St. Joseph',
      draftPick: '#1',
      draftedBy: 'Minnesota Timberwolves',
      team: teams[17].name,
    },
    {
      id: uuidv4(),
      name: 'Rudy Gobert',
      position: 'C',
      highSchool: 'Cholet Basket (France)',
      draftPick: '#27',
      draftedBy: 'Denver Nuggets',
      team: teams[17].name,
    },
    {
      id: uuidv4(),
      name: 'Zion Williamson',
      position: 'PF',
      highSchool: 'Spartanburg Day',
      draftPick: '#1',
      draftedBy: 'New Orleans Pelicans',
      team: teams[18].name,
    },
    {
      id: uuidv4(),
      name: 'CJ McCollum',
      position: 'PG | SG',
      highSchool: 'GlenOak',
      draftPick: '#10',
      draftedBy: 'Portland Trail Blazers',
      team: teams[18].name,
    },
    {
      id: uuidv4(),
      name: 'Brandon Ingram',
      position: 'SF | PF',
      highSchool: 'Kinston',
      draftPick: '#2',
      draftedBy: 'Los Angeles Lakers',
      team: teams[18].name,
    },
    {
      id: uuidv4(),
      name: 'Jonas Valanciunas',
      position: 'C',
      highSchool: 'Lietuvos Rytas (Lithuania)',
      draftPick: '#5',
      draftedBy: 'Toronto Raptors',
      team: teams[18].name,
    },
    {
      id: uuidv4(),
      name: 'Herbert Jones',
      position: 'SF | PF',
      highSchool: 'Hale County',
      draftPick: '#35',
      draftedBy: 'New Orleans Pelicans',
      team: teams[18].name,
    },
    {
      id: uuidv4(),
      name: 'Jalen Brunson',
      position: 'PG | SG',
      highSchool: 'Adlai Stevenson',
      draftPick: '#33',
      draftedBy: 'Dallas Mavericks',
      team: teams[19].name,
    },
    {
      id: uuidv4(),
      name: 'Donte DiVincenzo',
      position: 'SG',
      highSchool: 'Salesianum',
      draftPick: '#17',
      draftedBy: 'Milwaukee Bucks',
      team: teams[19].name,
    },
    {
      id: uuidv4(),
      name: 'OG Anunoby',
      position: 'SF',
      highSchool: 'Jeffrey\'s Grove',
      draftPick: '#23',
      draftedBy: 'Toronto Raptors',
      team: teams[19].name,
    },
    {
      id: uuidv4(),
      name: 'Julius Randle',
      position: 'PF | C',
      highSchool: 'Prestonwood Christian',
      draftPick: '#7',
      draftedBy: 'Los Angeles Lakers',
      team: teams[19].name,
    },
    {
      id: uuidv4(),
      name: 'Isaiah Hartenstein',
      position: 'PF | C',
      highSchool: 'Artland Dragons (Germany)',
      draftPick: '#43',
      draftedBy: 'Houston Rockets',
      team: teams[19].name,
    },
    {
      id: uuidv4(),
      name: 'Shai Gilgeous-Alexander',
      position: 'PG | SG',
      highSchool: 'Hamilton Heights Christian',
      draftPick: '#11',
      draftedBy: 'Charlotte Hornets',
      team: teams[20].name,
    },
    {
      id: uuidv4(),
      name: 'Josh Giddey',
      position: 'SG | SF',
      highSchool: 'Adelaide 36ers (Australia)',
      draftPick: '#6',
      draftedBy: 'Oklahoma City Thunder',
      team: teams[20].name,
    },
    {
      id: uuidv4(),
      name: 'Luguentz Dort',
      position: 'SG | SF',
      highSchool: 'Athlete Institute',
      draftPick: 'Undrafted',
      draftedBy: '',
      team: teams[20].name,
    },
    {
      id: uuidv4(),
      name: 'Jalen Williams',
      position: 'SG | PF',
      highSchool: 'Perry',
      draftPick: '#12',
      draftedBy: 'Oklahoma City Thunder',
      team: teams[20].name,
    },
    {
      id: uuidv4(),
      name: 'Chet Holmgren',
      position: 'PF | C',
      highSchool: 'Minnehaha Academy',
      draftPick: '#2',
      draftedBy: 'Oklahoma City Thunder',
      team: teams[20].name,
    },
    {
      id: uuidv4(),
      name: 'Jalen Suggs',
      position: 'PG | SG',
      highSchool: 'Minnehaha Academy',
      draftPick: '#5',
      draftedBy: 'Orlando Magic',
      team: teams[21].name,
    },
    {
      id: uuidv4(),
      name: 'Gary Harris',
      position: 'SG',
      highSchool: 'Hamilton Southeastern',
      draftPick: '#19',
      draftedBy: 'Chicago Bulls',
      team: teams[21].name,
    },
    {
      id: uuidv4(),
      name: 'Franz Wagner',
      position: 'SF',
      highSchool: 'Alba Berlin (Germany)',
      draftPick: '#8',
      draftedBy: 'Orlando Magic',
      team: teams[21].name,
    },
    {
      id: uuidv4(),
      name: 'Paolo Banchero',
      position: 'PF',
      highSchool: 'O\'Dea',
      draftPick: '#1',
      draftedBy: 'Orlando Magic',
      team: teams[21].name,
    },
    {
      id: uuidv4(),
      name: 'Wendell Carter Jr.',
      position: 'PF | C',
      highSchool: 'Pace Academy',
      draftPick: '#7',
      draftedBy: 'Chicago Bulls',
      team: teams[21].name,
    },
    {
      id: uuidv4(),
      name: 'Tyrese Maxey',
      position: 'PG | SG',
      highSchool: 'South Garland',
      draftPick: '#21',
      draftedBy: 'Philadelphia 76ers',
      team: teams[22].name,
    },
    {
      id: uuidv4(),
      name: 'Kyle Lowry',
      position: 'PG | SG',
      highSchool: 'Cardinal Dougherty',
      draftPick: '#24',
      draftedBy: 'Memphis Grizzlies',
      team: teams[22].name,
    },
    {
      id: uuidv4(),
      name: 'Kelly Oubre Jr.',
      position: 'SF',
      highSchool: 'Findlay Prep',
      draftPick: '#15',
      draftedBy: 'Atlanta Hawks',
      team: teams[22].name,
    },
    {
      id: uuidv4(),
      name: 'Tobias Harris',
      position: 'SF | PF',
      highSchool: 'Half Hollow Hills West',
      draftPick: '#19',
      draftedBy: 'Charlotte Bobcats',
      team: teams[22].name,
    },
    {
      id: uuidv4(),
      name: 'Joel Embiid',
      position: 'C',
      highSchool: 'The Rock School',
      draftPick: '#3',
      draftedBy: 'Philadelphia 76ers',
      team: teams[22].name,
    },
    {
      id: uuidv4(),
      name: 'Devin Booker',
      position: 'PG | SG',
      highSchool: 'Moss Point',
      draftPick: '#13',
      draftedBy: 'Phoenix Suns',
      team: teams[23].name,
    },
    {
      id: uuidv4(),
      name: 'Bradley Beal',
      position: 'PG | SG',
      highSchool: 'Chaminade College',
      draftPick: '#3',
      draftedBy: 'Washington Wizards',
      team: teams[23].name,
    },
    {
      id: uuidv4(),
      name: 'Grayson Allen',
      position: 'PG | SG | SF',
      highSchool: 'Providence School',
      draftPick: '#21',
      draftedBy: 'Utah Jazz',
      team: teams[23].name,
    },
    {
      id: uuidv4(),
      name: 'Kevin Durant',
      position: 'SG | SF | PF',
      highSchool: 'Montrose Christian',
      draftPick: '#2',
      draftedBy: 'Seattle SuperSonics',
      team: teams[23].name,
    },
    { 
      id: uuidv4(),
      name: 'Jusuf Nurkic',
      position: 'C',
      highSchool: 'Cedevita (Croatia)',
      draftPick: '#16',
      draftedBy: 'Chicago Bulls',
      team: teams[23].name,
    },
    {
      id: uuidv4(),
      name: 'Scoot Henderson',
      position: 'PG',
      highSchool: 'Carlton Kell',
      draftPick: '#3',
      draftedBy: 'Portland Trail Blazers',
      team: teams[24].name,
    },
    {
      id: uuidv4(),
      name: 'Anfernee Simons',
      position: 'PG | SG',
      highSchool: 'IMG Academy',
      draftPick: '#24',
      draftedBy: 'Portland Trail Blazers',
      team: teams[24].name,
    },
    {
      id: uuidv4(),
      name: 'Shaedon Sharpe',
      position: 'SG | SF',
      highSchool: 'Dream City Christian',
      draftPick: '#7',
      draftedBy: 'Portland Trail Blazers',
      team: teams[24].name,
    },
    {
      id: uuidv4(),
      name: 'Jerami Grant',
      position: 'SF | PF',
      highSchool: 'DeMatha Catholic',
      draftPick: '#39',
      draftedBy: 'Philadelphia 76ers',
      team: teams[24].name,
    },
    {
      id: uuidv4(),
      name: 'Deandre Ayton',
      position: 'C',
      highSchool: 'Hillcrest Prep',
      draftPick: '#1',
      draftedBy: 'Phoenix Suns',
      team: teams[24].name,
    },
    {
      id: uuidv4(),
      name: 'De\'Aaron Fox',
      position: 'PG',
      highSchool: 'Cypress Lakes',
      draftPick: '#5',
      draftedBy: 'Sacramento Kings',
      team: teams[25].name,
    },
    {
      id: uuidv4(),
      name: 'Kevin Huerter',
      position: 'SG | SF',
      highSchool: 'Shenendehowa',
      draftPick: '#19',
      draftedBy: 'Atlanta Hawks',
      team: teams[25].name,
    },
    {
      id: uuidv4(),
      name: 'Harrison Barnes',
      position: 'SF | PF',
      highSchool: 'Ames',
      draftPick: '#7',
      draftedBy: 'Golden State Warriors',
      team: teams[25].name,
    },
    {
      id: uuidv4(),
      name: 'Keegan Murray',
      position: 'SF | PF',
      highSchool: 'Prairie',
      draftPick: '#4',
      draftedBy: 'Sacramento Kings',
      team: teams[25].name,
    },
    {
      id: uuidv4(),
      name: 'Domantas Sabonis',
      position: 'PF | C',
      highSchool: 'Unicaja Málaga (Spain)',
      draftPick: '#11',
      draftedBy: 'Orlando Magic',
      team: teams[25].name,
    },
    {
      id: uuidv4(),
      name: 'Tre Jones',
      position: 'PG',
      highSchool: 'Apple Valley',
      draftPick: '#41',
      draftedBy: 'San Antonio Spurs',
      team: teams[26].name,
    },
    {
      id: uuidv4(),
      name: 'Devin Vassell',
      position: 'SG | SF',
      highSchool: 'Peachtree Ridge',
      draftPick: '#11',
      draftedBy: 'San Antonio Spurs',
      team: teams[26].name,
    },
    {
      id: uuidv4(),
      name: 'Julian Champagnie',
      position: 'SF',
      highSchool: 'Bishop Loughlin',
      draftPick: 'Undrafted',
      draftedBy: '',
      team: teams[26].name,
    },
    {
      id: uuidv4(),
      name: 'Jeremy Sochan',
      position: 'SF | PF',
      highSchool: 'La Lumiere School',
      draftPick: '#9',
      draftedBy: 'San Antonio Spurs',
      team: teams[26].name,
    },
    {
      id: uuidv4(),
      name: 'Victor Wembanyama',
      position: 'PF | C',
      highSchool: 'Nanterre 92 (France)',
      draftPick: '#1',
      draftedBy: 'San Antonio Spurs',
      team: teams[26].name,
    },
    {
      id: uuidv4(),
      name: 'Immanuel Quickley',
      position: 'PG | SG',
      highSchool: 'John Carroll',
      draftPick: '#25',
      draftedBy: 'Oklahoma City Thunder',
      team: teams[27].name,
    },
    {
      id: uuidv4(),
      name: 'Gary Trent Jr.',
      position: 'SG',
      highSchool: 'Prolific Prep',
      draftPick: '#37',
      draftedBy: 'Sacramento Kings',
      team: teams[27].name,
    },
    {
      id: uuidv4(),
      name: 'RJ Barrett',
      position: 'SG | SF',
      highSchool: 'Montverde Academy',
      draftPick: '#3',
      draftedBy: 'New York Knicks',
      team: teams[27].name,
    },
    {
      id: uuidv4(),
      name: 'Scottie Barnes',
      position: 'SG | SF | PF',
      highSchool: 'Montverde Academy',
      draftPick: '#4',
      draftedBy: 'Toronto Raptors',
      team: teams[27].name,
    },
    {
      id: uuidv4(),
      name: 'Jakob Poeltl',
      position: 'C',
      highSchool: 'Arkadia Traiskirchen Lions (Austria)',
      draftPick: '#9',
      draftedBy: 'Toronto Raptors',
      team: teams[27].name,
    },
    {
      id: uuidv4(),
      name: 'Keyonte George',
      position: 'PG | SG',
      highSchool: 'IMG Academy',
      draftPick: '#16',
      draftedBy: 'Utah Jazz',
      team: teams[28].name,
    },
    {
      id: uuidv4(),
      name: 'Collin Sexton',
      position: 'PG | SG',
      highSchool: 'Pebblebrook',
      draftPick: '#8',
      draftedBy: 'Cleveland Cavaliers',
      team: teams[28].name,
    },
    {
      id: uuidv4(),
      name: 'Lauri Markkanen',
      position: 'SF | PF',
      highSchool: 'Helsinki Basketball Academy (Finland)',
      draftPick: '#7',
      draftedBy: 'Minnesota Timberwolves',
      team: teams[28].name,
    },
    {
      id: uuidv4(),
      name: 'John Collins',
      position: 'PF',
      highSchool: 'Cardinal Newman',
      draftPick: '#19',
      draftedBy: 'Atlanta Hawks',
      team: teams[28].name,
    },
    {
      id: uuidv4(),
      name: 'Walker Kessler',
      position: 'C',
      highSchool: 'Woodward Academy',
      draftPick: '#22',
      draftedBy: 'Memphis Grizzlies',
      team: teams[28].name,
    },
    {
      id: uuidv4(),
      name: 'Tyus Jones',
      position: 'PG',
      highSchool: 'Apple Valley',
      draftPick: '#24',
      draftedBy: 'Cleveland Cavaliers',
      team: teams[29].name,
    },
    {
      id: uuidv4(),
      name: 'Jordan Poole',
      position: 'PG | SG',
      highSchool: 'La Lumiere School',
      draftPick: '#28',
      draftedBy: 'Golden State Warriors',
      team: teams[29].name,
    },
    {
      id: uuidv4(),
      name: 'Deni Avdija',
      position: 'SF | PF',
      highSchool: 'Maccabi Tel Aviv (Israel)',
      draftPick: '#9',
      draftedBy: 'Washington Wizards',
      team: teams[29].name,
    },
    {
      id: uuidv4(),
      name: 'Kyle Kuzma',
      position: 'SF | PF',
      highSchool: 'Rise Academy',
      draftPick: '#27',
      draftedBy: 'Brooklyn Nets',
      team: teams[29].name,
    },
    {
      id: uuidv4(),
      name: 'Marvin Bagley III',
      position: 'PF | C',
      highSchool: 'Sierra Canyon',
      draftPick: '#2',
      draftedBy: 'Sacramento Kings',
      team: teams[29].name,
    },
  ]

  const [players, setPlayers] = useState(starters)

  function playerDelete(id) {
      setPlayers(players.filter(player => player.id !== id))
  }

  function changeTeamColor(color, id){
    setTeams(teams.map(team => {
      if (team.id === id) {
        team.color = color
      }
      return team
    }))
  }

  //function saveTeam(newTeam){
  //  setTeams([...teams, {...newTeam, id: uuidv4()}])
  //}

  function playerFavorite(id){
    setPlayers(players.map(player => {
      if (player.id === id) {
        player.favorite = !player.favorite
      }
      return player
    }))
  }

  return (
    <div className="App">
      <Banner />

      <Form 
        //saveTeam={saveTeam}
        teams={teams.map(team => team.name)} 
        playerCreated={player => setPlayers([...players, player])} 
      />

      {teams.map(team => <Team 
        changeColor={changeTeamColor}
        key={team.name} 
        id={team.id}
        name={team.name} 
        color={team.color} 
        championships={team.championships}
        players={players.filter(player => player.team === team.name)}
        deleting={playerDelete}
        onFav={playerFavorite}
      />)}

      <Footer />
    </div>
  );
}

export default App;
